name: Solution Deployment/Creation Enhancement
description: Submit an enhancement for the ArcGIS Solutions Deployment app, Creation app or Solution Item Tools.
labels: ["Type: Enhancement", "Product: ArcGIS Solutions App"]
#title: ""
#assignees: [""]
projects: ["chris-fox/3"]
body:
  - type: markdown
    attributes:
      value: |
        - Please [check for existing issues](https://devtopia.esri.com/WebGIS/solutions-web-development/issues) to avoid duplicates. If someone has already opened an issue for what you are requesting, please add a comment to the existing issue instead of creating a new one.
  - type: dropdown
    id: solutions-app
    validations:
      required: true
    attributes:
      label: Solutions app/tools
      multiple: false
      description: Select in which app or tool you are observing this issue.
      options:
        - ArcGIS Solutions Deployment app
        - ArcGIS Solutions Creation app
        - Solution Item Tools
  - type: textarea
    id: describe
    attributes:
      label: Describe requirements
      description: Description of what's missing and what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe any alternative solutions or features you've considered using instead.
    validations:
      required: true
  - type: textarea
    id: relevant
    attributes:
      label: Other relevant info
      description: Add any other context or screenshots about the feature request.
    validations:
      required: false
  - type: dropdown
    id: priority-impact
    validations:
      required: true
    attributes:
      label: Priority impact
      multiple: false
      description: What is the impact to you or your team?
      options:
        - Low - not time sensitive
        - Medium - want for an upcoming release
        - High - want for next release
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: How does the issue effect your team or your work? Can range from minor to blocking or prohibiting workflows. Helps us prioritize what we'll work on and communicate with the responsible party first.
    validations:
      required: false
