name: Troubleshooting Assistance
description: Request assistance in troubleshooting an issue with a configuration of ArcGIS impacting an ArcGIS Solution or an issue with packaging or deploying a solution.
labels: ["Type: Troubleshooting Assistance"]
#title: ""
#assignees: [""]
projects: ["chris-fox/4"]
body:
  - type: markdown
    attributes:
      value: |
        For testing tips & tricks, please check the [Wiki](https://devtopia.esri.com/WebGIS/solutions-web-development/wiki/Testing-Tips-&-Tricks).
  - type: dropdown
    id: esri-product
    validations:
      required: true
    attributes:
      label: Esri product
      multiple: true
      description: Select the products you need help troubleshooting.
      options:
        - N/A
        - ArcGIS Arcade
        - ArcGIS Dashboards
        - ArcGIS Data Pipelines
        - ArcGIS Enterprise
        - ArcGIS Experience Builder
        - ArcGIS Field Apps
        - ArcGIS Hub
        - ArcGIS Indoors
        - ArcGIS Insights
        - ArcGIS Instant Apps
        - ArcGIS Knowledge
        - ArcGIS Living Atlas
        - ArcGIS Map Viewer
        - ArcGIS Maps SDK for JavaScript
        - ArcGIS Mission
        - ArcGIS Monitor
        - ArcGIS Online
        - ArcGIS Pro
        - ArcGIS QuickCapture
        - ArcGIS Scene Viewer
        - ArcGIS Site Scan
        - ArcGIS StoryMaps
        - ArcGIS Survey123
        - ArcGIS Velocity
        - ArcGIS Web AppBuilder
        - ArcGIS Web Editor
        - ArcGIS Workflow Manager
        - Smart Forms (Editor)
        - Other
  - type: input
    id: solution
    attributes:
      label: Solutions impacted
      description: What solutions need troubleshooting?
  - type: textarea
    id: describe
    attributes:
      label: Describe the issue
      description: Description of the issue you are seeing in a configuration of ArcGIS or with packaging or deploying a solution.
    validations:
      required: true
  - type: textarea
    id: troubleshooting
    attributes:
      label: Troubleshooting steps
      description: Describe the steps you have already tried to narrow down or workaround the issue.
    validations:
      required: true
  - type: textarea
    id: links
    attributes:
      label: Item links
      description: Provide links to the items that need troubleshooting. Please provide the organization url if it is not clear in the item's url.
    validations:
      required: true
