name: Technical Review
description: Request a technical review of one or more information products or technical patterns used in an ArcGIS Solution.
labels: ["Type: Technical Review"]
#title: ""
#assignees: [""]
projects: ["chris-fox/4"]
body:
  - type: dropdown
    id: esri-product
    validations:
      required: true
    attributes:
      label: Esri product
      multiple: true
      description: Select the products with configurations that you would like reviewed.
      options:
        - N/A
        - ArcGIS Arcade
        - ArcGIS Dashboards
        - ArcGIS Data Pipelines
        - ArcGIS Enterprise
        - ArcGIS Experience Builder
        - ArcGIS Field Apps
        - ArcGIS Hub
        - ArcGIS Indoors
        - ArcGIS Insights
        - ArcGIS Instant Apps
        - ArcGIS Knowledge
        - ArcGIS Living Atlas
        - ArcGIS Map Viewer
        - ArcGIS Maps SDK for JavaScript
        - ArcGIS Mission
        - ArcGIS Monitor
        - ArcGIS Online
        - ArcGIS Pro
        - ArcGIS QuickCapture
        - ArcGIS Scene Viewer
        - ArcGIS Site Scan
        - ArcGIS StoryMaps
        - ArcGIS Survey123
        - ArcGIS Velocity
        - ArcGIS Web AppBuilder
        - ArcGIS Web Editor
        - ArcGIS Workflow Manager
        - Smart Forms (Editor)
        - Other
  - type: input
    id: solution
    attributes:
      label: Solutions impacted
      description: What solutions are you requesting a review for?
  - type: textarea
    id: describe
    attributes:
      label: Describe requested review
      description: Description of the review you are requesting. For example, a complete review of the information products or to review a specific technical pattern in one or more information products.
    validations:
      required: true
  - type: textarea
    id: links
    attributes:
      label: Information product links
      description: Include the links to the information products you would like to be reviewed. Please provide the organization url if it is not clear in the item's url.
    validations:
      required: true
