name: Implementation Research
description: Request assistance in researching an ArcGIS capability or recommend a technical approach to accomplish a desired workflow in an ArcGIS Solution.
labels: ["Type: Implementation Research"]
#title: ""
#assignees: [""]
projects: ["chris-fox/4"]
body:
  - type: dropdown
    id: esri-product
    validations:
      required: true
    attributes:
      label: Esri product
      multiple: true
      description: Select the products you are using or considering using in your implementation.
      options:
        - N/A
        - ArcGIS Arcade
        - ArcGIS Dashboards
        - ArcGIS Data Pipelines
        - ArcGIS Enterprise
        - ArcGIS Experience Builder
        - ArcGIS Field Apps
        - ArcGIS Hub
        - ArcGIS Indoors
        - ArcGIS Insights
        - ArcGIS Instant Apps
        - ArcGIS Knowledge
        - ArcGIS Living Atlas
        - ArcGIS Map Viewer
        - ArcGIS Maps SDK for JavaScript
        - ArcGIS Mission
        - ArcGIS Monitor
        - ArcGIS Online
        - ArcGIS Pro
        - ArcGIS QuickCapture
        - ArcGIS Scene Viewer
        - ArcGIS Site Scan
        - ArcGIS StoryMaps
        - ArcGIS Survey123
        - ArcGIS Velocity
        - ArcGIS Web AppBuilder
        - ArcGIS Web Editor
        - ArcGIS Workflow Manager
        - Smart Forms (Editor)
        - Other
  - type: input
    id: solution
    attributes:
      label: Solutions impacted
      description: What solutions are you requesting reasearch assistance for?
  - type: textarea
    id: describe
    attributes:
      label: Describe capability or workflow
      description: Description of the capability you want to learn more about or the workflow you are trying to accomplish in the context of your solution.
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current approach
      description: Describe how you are currently solving this workflow in your solution.
    validations:
      required: false
  - type: textarea
    id: relevant
    attributes:
      label: Other relevant info
      description: Add any other context, screenshots, design documents, or item links related to the implementation.
    validations:
      required: false
