name: Update priority on project board

on:
  repository_dispatch:
    types: [status_update]

permissions:
  issues: write
  contents: read

jobs:            
  update_priority:
    runs-on: ubuntu-latest
    steps:
      - name: Update priority
        id: update_status
        uses: github/update-project-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          organization: chris-fox
          project_number: 4
          content_id: ${{ github.event.client_payload.command.resource.id }}
          field: Priority
          value: High